### PR TITLE
Feature/backend firestore random method

### PR DESCRIPTION
**Pull request by akshire**
# Description

### What has been changed?

This PR introduces a `random` function in the `FirestoreRecipesRepository`, allowing random recipes to be fetched from Firestore. Here’s how randomness is achieved:

- A unique UID is generated by calling `generateRandomUID()`.
- This UID serves as a starting point, with Firestore queried to return the recipe closest to it in the database.
- By fetching the closest matching recipe along with a specified number (`nbOfElements`) of additional entries, a randomized recipe set is achieved, adding variety and enhancing user experience.

### Why was this change made?

This change is part of a migration effort from the existing MealDB repository to Firestore, offering greater control over recipe data and enhanced functionality.

### Main Function: `random`

```kotlin
override fun random(
    nbOfElements: Int,
    onSuccess: (List<Recipe>) -> Unit,
    onFailure: (Exception) -> Unit
) {
    require(nbOfElements > 0) { LIMIT_MUST_BE_POSITIVE_MESSAGE }

    val randomUID = generateRandomUID()
    Log.d("FirestoreRecipesRepository", "Generated Random UID: $randomUID")

    db.collection(FIRESTORE_COLLECTION_NAME)
        .whereGreaterThanOrEqualTo(FieldPath.documentId(), randomUID)
        .limit(nbOfElements.toLong())
        .get()
        .addOnCompleteListener { task ->
            if (task.isSuccessful) {
                val recipes = task.result?.documents?.mapNotNull { documentToRecipe(it) } ?: emptyList()
                onSuccess(recipes)
            } else {
                task.exception?.let { onFailure(it) }
            }
        }
}
```

- The function validates the `nbOfElements` parameter to ensure it’s positive.
- It then generates a random UID and queries Firestore for recipes with IDs greater than or equal to this UID.
- Recipes are returned as a list, or an error is passed to `onFailure` if encountered.

## Checklist

- [x] Added comprehensive tests, covering valid recipe retrieval, empty results, and error handling with Firestore.
- [x] Updated documentation with detailed descriptions of function usage and requirements.
- [x] Passed all CI checks.
- [x] Linked issue/feature: #138

### CODE REVIEW

**Comment by anaselmadhi** [comment]
Thank you for your effort on this PR! The introduction of a random method in the FirestoreRecipesRepository is a valuable addition that enhances the app's functionality by allowing users to fetch random recipes. This feature aligns well with the migration to Firestore and brings a more dynamic experience for end-users.

## Pros:
- Effective Randomization: Using generateRandomUID() as a starting point for querying Firestore simplifies the randomization process. This approach is efficient and avoids unnecessary complexity.
- Input Validation: The check to ensure nbOfElements is positive is a great way to handle potential misuse of the function.
- Error Handling: The onFailure callback is well-implemented, allowing smooth handling of errors and improved reliability.
- Comprehensive Testing: The PR includes extensive tests that cover a range of scenarios, ensuring robustness and reliability.

## Suggestions for Improvement:
- Documentation: While the PR is documented, consider adding a brief comment inside the random method to clarify why generateRandomUID() is used, which can aid future developers in understanding the randomization logic.
- Randomization Bias: If Firestore’s UID distribution is not perfectly uniform, this approach might introduce slight bias. It might be worthwhile to explore this aspect further to ensure consistency in randomization.
- Enhanced Flexibility: Adding an optional parameter to allow custom UIDs as starting points could add flexibility for various use cases, making the method more versatile.

## Tests:
- Coverage: The tests are well-structured and cover key aspects like valid recipe retrieval, empty results, and error handling.
- Additional Edge Cases: It could be beneficial to test edge cases for high or low values of nbOfElements to ensure consistent behavior in all scenarios.

## Final Thoughts:
Overall, this PR achieves its goals effectively, with a clean and maintainable implementation. With minor improvements in documentation and flexibility, this random method will be a strong asset to the FirestoreRecipesRepository.

## Suggested Labels:
✅ Ready to Merge: Once the minor documentation and optional suggestions are considered, this PR will be ready to be merged.

**Comment by akshire** [comment]
I added documentation as suggested, this method will be further modified I think if we decide to do some user focused suggestions so this is just to have something approximately random to fetch recipes.

**Comment by anaselmadhi** [comment]
Alright, thanks for adding the documentation! This works for now, and we can adjust it if we move towards more user-focused suggestions. Good to merge!

**Review by anaselmadhi — APPROVED** [review]
Alright, thanks for adding the documentation! This works for now, and we can adjust it if we move towards more user-focused suggestions. Good to merge!

**Pull request merged**
