### PR TITLE
Feature/img url

### PR DESCRIPTION
**Pull request by Ylanv**
# Description

## **What has been changed?**
   - Added a new `getImageUrl` method in `FirestoreRecipesRepository` that retrieves the URL of an image stored in Firebase Storage for each recipe.
   - Added a new `url` field to the `Ingredient` model and updated the code to save this field in Firestore. 

  - Also modified `PublishRecipe()` to retrieve the image `url` before building the recipe, ensuring the image link is available as part of the recipe data.

## **Why was this change made?**
  - With this PR, we have achieved full independence for managing recipes: we can now store our own recipes and create them directly within the app. 🥳 
   - Storing recipe images as `Bitmap` objects caused memory issues. For example, a high-quality `.jpg` image in `Bitmap` format consumes significant memory, which is not suitable when fetching recipes in batches.
   - To address this, the image is now stored in Firebase Storage when a recipe is created, and a URL is generated and added to the recipe’s data as a new `url` parameter.
   - The app can now load images from URLs, which improves memory usage and batch retrieval efficiency. Images are loaded using `rememberAsyncImagePainter`, avoiding direct storage of `Bitmap` objects.

   **Code for Image Display:**
   ```kotlin
   Image(
       painter = rememberAsyncImagePainter(
           model = if (displayCard1) currentRecipe?.url else nextRecipe?.url
       ),
       contentDescription = stringResource(R.string.recipe_image),
       modifier = Modifier.fillMaxSize().testTag(RECIPE_IMAGE_1),
       contentScale = ContentScale.Crop,
   )
   ```

   - **Trade-offs**: Fetching an image by URL introduces a slight delay compared to direct `Bitmap` storage, but in practice, the image retrieval is quick and provides a smooth user experience.
   - To integrate this new structure, the entire recipes database was modified with a script.

   **Script Details:**
   - The provided script updates each recipe to include the new image URL by using `getImageUrl`.
   - Note: Running such scripts requires caution, as they can impact database integrity. For future use, refer to @akshire  or @Ylanv  for guidance.
# Schema
Here is a simple diagram that outlines the execution flow for publishing a recipe.

image

# Important 
The FireStore collection `recipes with images` is now our production database, if you want to do testing please create a test collections following the [Wiki](https://github.com/PlateSwipe/PlateSwipe/wiki/Testing-with-the-Firestore-DB) made by @akshire . 

## Checklist
- [x] Tests added.
- [x] Documentation updated.
- [x] All CI checks passed.
- [x] Linked issue/feature (if applicable): #200 

### **Note**
 Since this code is no longer part of the app, I’m using this PR to document the approach I used.
### **Purpose**
We had a database in which each recipe lacked a URL linking to its image in storage. This script retrieves each recipe, obtains the image URL, and updates the recipe to include the new URL.
### Composable
This composable is called inside `MainActivity.kt`, it display a button that allow to start the process
```kotlin
@Composable
fun TestButton() {
    var recipes = mutableListOf<Recipe>()
    Button(
        onClick = {
            val firestoreRecipesRepository = FirestoreRecipesRepository(Firebase.firestore)
            val imageRepository = ImageRepositoryFirebase(com.google.firebase.Firebase.storage)
            firestoreRecipesRepository.getAllRecipe(onSuccess = {
                recipes = it.toMutableList()
                Log.d("Test", recipes.size.toString())
                recipes.forEach { recipes ->
                    imageRepository.getImageUrl(recipes.idMeal,"Main",ImageDirectoryType.RECIPE,onSuccess = { uri ->
                        recipes.url = uri.toString()
                        Log.d("Test", recipes.url!!)
                        firestoreRecipesRepository.addRecipe(recipes, onSuccess = {
                            Log.d("Test", "success")}, onFailure = {Log.d("Test", "errur")})
                    }, onFailure = {
                        Log.d("Test", "errir")
                    })
                }
            })


        }){
        Text("Test")
    }
}
```

### Fetch method 
This method was places inside `FirestoreRecipesRepository.kt` it allow to fetch all the document in one go.
```kotlin
fun getAllRecipe(onSuccess: (List<Recipe>) -> Unit) {
    db.collection("recipes with images")
        .get()
        .addOnSuccessListener { doc ->
          val recipes = mutableListOf<Recipe>()
          for (document in doc) {
            val recipe = documentToRecipe(document)
            if (recipe != null) {
              recipes.add(recipe)
              Log.d("FirestoreRecipesRepository", "getAllRecipe: ${recipe.strMeal}")
            }
          }
          onSuccess(recipes)
        }
        .addOnFailureListener { Log.e("FirestoreRecipesRepository", "Error getting documents", it) }
  }
```

### CODE REVIEW

**Comment by anaselmadhi** [comment]
# ImageRepository Interface
## Addition of the getImageUrl Method:
- This method is useful for retrieving the download URL of an image stored in Firebase. The documentation is thorough and clearly describes the parameters, improving readability and usability.
- Make sure that parameter types (imageDirectoryUID, imageName, imageDirectoryType) align with Firebase Storage requirements to avoid potential conversion issues.
## ImageRepositoryFirebase Implementation
- Implementation of getImageUrl:
   - The code correctly uses addOnSuccessListener and addOnFailureListener to handle asynchronous callbacks, which is a good practice with Firebase.
   - Error handling is well-managed, but the error message could be more specific to help with debugging.
## publishRecipe Method in RecipeRepository
- Improvements Related to Image Upload and Retrieval:
   - The method uses getImageUrl after uploading the image to retrieve the URL and add it to the recipe, which centralizes the image URL in the database.
   - The use of onSuccess and onFailure callbacks to handle recipe addition and URL retrieval is well-structured, ensuring that the status is updated correctly based on potential errors.
   - Suggestion: It could be beneficial to handle the image upload and retrieval in a utility function or within a coroutine to simplify the publishRecipe method.
## FirestoreRecipesRepository
- Addition of URL in Recipe Model:
   - Retrieving FIRESTORE_RECIPE_URL from Firestore is a relevant addition that maintains each recipe's image information within the model.
   - The code is well-structured to map Firestore data into a Recipe object. Managing url is consistent with other recipe properties.
## Recipe Data Class
- Addition of the url Property:
   - Adding the url property to the Recipe class allows each recipe to be associated with an image, which is essential for displaying images in the app.
   - The modification in toFirestoreData to include url is correct and ensures the url property is saved in Firestore.
## RecipeBuilder
- Addition of setUrl and getUrl Methods:
   - The new setUrl and getUrl methods in RecipeBuilder enable seamless URL management and are well-integrated into the recipe-building pattern.
   - The additions to the build function are consistent, ensuring that the URL is considered when constructing a Recipe object.
## Usage in RecipeDisplay
- Image Display:
   - The changes to use currentRecipe?.url and nextRecipe?.url are appropriate, ensuring the correct image is displayed for each recipe.
   - Suggestion: Consider adding a check if url is null to prevent potential display errors.

## ImageRepositoryFirebase Tests: 
- Improve Mock Setup Consistency:
   - Problem: Mocking of Firebase tasks like mockTaskUri with success and failure listeners is repeated across multiple tests. This can make the code verbose and harder to maintain.
   - Suggestion: Create helper methods for success and failure listeners to reduce code duplication. This will make the tests more concise and easier to read.

- Enhance Assertion Messages:
  - Problem: The assertions lack custom messages, which can make debugging failures harder.
  - Suggestion: Add descriptive messages to assertions to help identify specific test failures.

- Refactor Hardcoded Test Data:
   - Problem: Strings like "https://example.com/test.jpg" are hardcoded in multiple places.
   - Suggestion: Define constants for URLs, error messages, and other repeated strings to avoid redundancy and improve readability.

##  RecipeBuilderTest
- Improve Consistency in Assertions:
   - Problem: Some assertions lack custom messages, making it harder to identify the failure context.
   - Suggestion: Add messages to assertions for better clarity during debugging.

**Comment by Ylanv** [comment]
# Addition of the getImageUrl Method:

> Make sure that parameter types (imageDirectoryUID, imageName, imageDirectoryType) align with Firebase Storage requirements to avoid potential conversion issues.

✔️

**Comment by Ylanv** [comment]
# ImageRepositoryFirebase Implementation

> Error handling is well-managed, but the error message could be more specific to help with debugging.

`Exception("Image download from Firebase storage has failed or image does not exist"))`

This message appears to convey the issue clearly. However, I welcome any suggestions you might have for improvement.

**Comment by Ylanv** [comment]
# Usage in RecipeDisplay

> Suggestion: Consider adding a check if url is null to prevent potential display errors.

I believe you're referring to the image displayed in the **SwipePage**. Typically, a recipe should not have a null URL. However, in the event that it does, the `rememberAsyncImagePainter` handles this by displaying a black image. This means the situation is already managed within the app's existing functionality.

**Comment by Ylanv** [comment]
# ImageRepositoryFirebase Tests:

> Suggestion: Create helper methods for success and failure listeners to reduce code duplication. This will make the tests more concise and easier to read.

I've moved the mocking of these two methods into the `setUp` call to eliminate redundancy. This should help streamline the tests and ensure consistency across each test case. ✔️ 

> Suggestion: Add descriptive messages to assertions to help identify specific test failures. 

The three assertions are:
```kotlin
assertEquals(testUri, resultUri)
```
```kotlin
assertTrue(failureException is Exception)
```
```kotlin
assertEquals("Image download from Firebase storage has failed or image does not exist", failureException?.message)
```

These seem straightforward to me, but please let me know if anything is unclear.

> Suggestion: Define constants for URLs, error messages, and other repeated strings to avoid redundancy and improve readability.

Done ✔️

**Review by anaselmadhi — APPROVED** [review]
Thank you for this PR and the suggested improvements. I’ve reviewed the changes, and everything looks good. The code is clear and well-structured, and the tests adequately cover the necessary cases. I’m approving this review. Great job!

**Pull request merged**
