### PR TITLE
Fix/text theme change correction

### PR DESCRIPTION
**Pull request by RagdollGoDown**
# MINOR FIX: theme incorrectly set for topbar and account screen username
## Description
- [x] What has been changed?
This pull request includes various updates to the UI components, particularly focusing on styling and layout improvements. The most important changes involve updating text styles, adding new constants for dimensions, and modifying layout components for better alignment and consistency.

### UI Styling and Layout Improvements:

* Updated text styles and added color properties in `EmptyScreen.kt` and `AccountScreen.kt` to use `titleMedium` and `onPrimary` color scheme. [[1]](diffhunk://#diff-98a09a8a8c59fb8a726ebaf91fbdb1d984cbe79b67fca2586f8aca60f228972fL30-R37) [[2]](diffhunk://#diff-ce6d9507450bcdb59bfa546d4015b53957ca28e5c49190fdc2ee6026414dd9c2L65-R66)
* Added new constants for dimensions in `C.kt`, including `TOP_BAR_TITLE_FONT_SIZE`.
* Imported additional layout and unit classes in `PlateSwipeScaffold.kt` to support new layout changes. [[1]](diffhunk://#diff-e7eccad8d7f7697fc4aba0798ca200b9207b720391e37d16b2eb0758f6266bd9R11) [[2]](diffhunk://#diff-e7eccad8d7f7697fc4aba0798ca200b9207b720391e37d16b2eb0758f6266bd9R29-R35)
* Modified `PlateSwipeTopBar` in `PlateSwipeScaffold.kt` to include height and font size properties, and adjusted text properties for better alignment and styling. [[1]](diffhunk://#diff-e7eccad8d7f7697fc4aba0798ca200b9207b720391e37d16b2eb0758f6266bd9L75-R83) [[2]](diffhunk://#diff-e7eccad8d7f7697fc4aba0798ca200b9207b720391e37d16b2eb0758f6266bd9L103-R114)
* Removed redundant `Row` component in `PlateSwipeTopBar` for cleaner layout.

- [x] Why was this change made?
Alot of different texts have been appearing too big due to a recent change to the titleLarge font. They were switched to the more appropriate titleMedium.
The color was defined, because with the addition of the onbackground and most of these texts having unspecied colors. This means they will default to the new onbackground color. To correct this I set it to onPrimary.

## Checklist
- [x] All CI checks passed.
- [x] Linked issue/feature (if applicable): #188

### CODE REVIEW

**Review by 2Fick — CHANGES_REQUESTED** [review]
It's a great move to add this typography for more flexibility, especially since the large text was simply unreadable. The changes applied to the Account page and the Topbar are working really well, and the text is much more readable now.

However, I think it would be good to apply these changes to the `EmptyScreen` as well. Right now, the titles are still using `titleLarge`. Here's a quick snippet for that:

```kotlin
@Composable
fun EmptyScreen(navigationActions: NavigationActions, title: String) {
    Scaffold(
        bottomBar = {
            BottomNavigationMenu(
                onTabSelect = { tab -> navigationActions.navigateTo(tab) },
                tabList = LIST_TOP_LEVEL_DESTINATIONS,
                selectedItem = navigationActions.currentRoute())
        }) { paddingValues ->
            Box(
                modifier = Modifier.fillMaxSize().padding(paddingValues),
                contentAlignment = Alignment.Center) {
                    Column(horizontalAlignment = Alignment.CenterHorizontally) {
                        Text(title, style = MaterialTheme.typography.headlineMedium) // Change here
                        Text("Work in progress... Stay tuned!", style = MaterialTheme.typography.bodyMedium)
                    }
                }
        }
}
```

The idea would be to swap `titleLarge` with `headlineMedium` in the `EmptyScreen` as well. Please give it a try and let's see how it looks!

**Comment by RagdollGoDown** [comment]
> It's a great move to add this typography for more flexibility, especially since the large text was simply unreadable. The changes applied to the Account page and the Topbar are working really well, and the text is much more readable now.
> 
> However, I think it would be good to apply these changes to the `EmptyScreen` as well. Right now, the titles are still using `titleLarge`. Here's a quick snippet for that:
> 
> ```kotlin
> @Composable
> fun EmptyScreen(navigationActions: NavigationActions, title: String) {
>     Scaffold(
>         bottomBar = {
>             BottomNavigationMenu(
>                 onTabSelect = { tab -> navigationActions.navigateTo(tab) },
>                 tabList = LIST_TOP_LEVEL_DESTINATIONS,
>                 selectedItem = navigationActions.currentRoute())
>         }) { paddingValues ->
>             Box(
>                 modifier = Modifier.fillMaxSize().padding(paddingValues),
>                 contentAlignment = Alignment.Center) {
>                     Column(horizontalAlignment = Alignment.CenterHorizontally) {
>                         Text(title, style = MaterialTheme.typography.headlineMedium) // Change here
>                         Text("Work in progress... Stay tuned!", style = MaterialTheme.typography.bodyMedium)
>                     }
>                 }
>         }
> }
> ```
> 
> The idea would be to swap `titleLarge` with `headlineMedium` in the `EmptyScreen` as well. Please give it a try and let's see how it looks!

I agree, I'll get right to it

**Comment by 2Fick** [comment]
It seems that everything looks good apart of the color of the back arrow. I wanted to know if it was intentional to change the color or a mistake ?
image

**Review by 2Fick — APPROVED** [review]
Now everything looks good to me !

**Pull request merged**
