### PR TITLE
Figma

### PR DESCRIPTION
**Pull request by Ylanv**
### What has been changed?
This PR updates the `README.md` with a link to the Figma design for **Milestone 1**, which showcases the current state of the app design. No new code is included in this PR.

### Why was this change made?
The purpose of this PR is to gather feedback from the team on the design of the app. I believe it's essential to get input from people in different fields to ensure the design is user-friendly, visually appealing, and aligned with the project's goals. Please feel free to provide comments on what you think, any areas that could be improved, and anything that seems unclear.

---

## Figma Details:
- **[User Flow](https://www.figma.com/design/lWFaH9B1YIkVyy45Cva9yk/M1?node-id=405-523&node-type=canvas&t=zmIyVCMKmiG04R5r-0)**: A flow chart of the app screens and navigation structure.
- **[Wireframe](https://www.figma.com/design/lWFaH9B1YIkVyy45Cva9yk/M1?node-id=0-1&node-type=canvas&t=zmIyVCMKmiG04R5r-0)**: A skeleton of each screen layout with minimal focus on color and design.
- **[Mockup](https://www.figma.com/design/lWFaH9B1YIkVyy45Cva9yk/M1?node-id=3-2&node-type=canvas&t=zmIyVCMKmiG04R5r-0)**: The final product design, showing the intended look and feel of the app.
- You can interact with the prototype by clicking the **Play button** in the top-right corner of Figma.

---

## Checklist
- [x] Linked the Figma design for **Milestone 1** in the `README`.
- [x] Requested design feedback from the team.

---

## Feedback Request
Your input is valuable! Please let me know:
- What do you think of the current design?
- Any suggestions for improvement?
- If there’s anything unclear or that needs more attention.

## Quick Overview:
I will display a few images below to give a quick overview of the design. However, I highly recommend going directly to the Figma link to get the best quality and freedom to navigate through the entire design.

### User flow
User flow

### Wireframe

Wireframe

### Mock up

Login Mockup

Search mockup

### CODE REVIEW

**Review by CapraSnitzel — COMMENTED** [review]
## Feedback
Great work on the Figma, it looks great. We can really see an evolution since the last version that was made for the Sprint 1.
Below, you will find some suggestions for the app and some personal opinions about the design:
#### Suggestions
1. It would be good to have an indicator for the price of the recipe in the Swipe page like when we search a recipe. That way, the user can already see if the recipe is expensive and he does not need to like the recipe and then check the price.. What do you think ?
2. I see that there is no screen where we can edit a certain ingredient from the virtual fridge. I think it would be useful to have a screen where we can modify it because sometimes people will give others some ingredients if they need them(for example, eggs).
#### Opinions
1. Personally, I don't like the fact that there are buttons to like or dislike, as well as the swipe feature (swipe left/right to dislike/like). I am leaning more towards only keeping the swipe.
3. I really like the fact that there is a filter for the searching of a recipe. This lets the user to search for recipes that are to his taste or in his budget or that need to be quick to do.
4. I also like the fact that we get to see then the ingredients will expire. This allows the user to better use his ingredients (prioritize the ones that are going to expire and not waste them)

**Comment by anaselmadhi** [comment]
# 1. Application Architecture (UI & Data Layer)
## Strengths:
The separation between the UI Layer and Data Layer is well-defined, making the architecture modular and scalable. Each ViewModel handles specific responsibilities, which contributes to clean code and easier maintenance.
The use of repositories for each data type (User, Recipe, Ingredient) promotes reusability and makes it straightforward to integrate with external APIs like MealDB and OpenFoodFact.
## Areas for Improvement:
Error Handling: It’s unclear how the design addresses error handling, especially when communicating with external APIs. Including a mechanism for error states in the ViewModel or Repository layer would make the app more robust.
Caching and Offline Support: Consider adding details on how data will be cached, especially for recipes and ingredients. This could improve the user experience by allowing offline access to previously fetched data.
# 2. User Flow (PlateSwipe Flow Chart)
## Strengths:
The flow chart is comprehensive and covers major app functionalities like “Search,” “Add New,” and “Account.” It’s visually clear and easy to follow, which helps in understanding the overall user journey.
The breakdown of actions, such as filtering recipes by budget or difficulty, shows a strong focus on user needs and customization, which enhances usability.
## Areas for Improvement:
Onboarding Experience: While the sign-in and sign-up flows are included, you might want to expand on the onboarding process to give new users an introduction to the app’s features. A quick tutorial or walkthrough could help improve initial user engagement.
Secondary Navigation: The flow from one feature to another is not always clear. For example, transitioning from the “Search” function to other parts of the app like “Account” or “Add New” could be streamlined. Consider adding more detail on how users can easily navigate between these sections.
# 3. User Stories
## Strengths:
The user stories are extensive and cover a wide variety of features. By categorizing them into sections like “Recipe,” “Ingredients,” and “Account Page,” you’ve ensured that different user needs are well-documented.
Prioritization labels (P0, P1, P2) are very helpful for the development team. This clear prioritization allows for focused development on high-impact features first, which is great for project management.
## Areas for Improvement:
Missing Edge Cases: Some user stories could benefit from more detailed edge cases. For instance, what happens if the user tries to publish a recipe without sufficient ingredients? Including these scenarios in the user stories can help prevent potential UX issues.
Usability Testing: It would be beneficial to include a plan for user testing within these stories. For example, user stories related to “Searching Recipes” and “Virtual Fridge” could specify testing goals to ensure these features meet user expectations in terms of responsiveness and ease of use.
# 4. UI Design (Screens and Components)
## Strengths:
The design is visually consistent, with a cohesive color palette and typography, making it easy to read and aesthetically pleasing. This shows attention to detail in the branding and overall user experience.
Key user flows, such as the “Swipe Page” and “Search Recipe Page,” are well thought-out, with clear icons and buttons that help guide users through their tasks seamlessly.
## Areas for Improvement:
Responsiveness: Consider adding design specifications for different screen sizes and orientations to ensure the UI adapts well across devices. For example, larger tablets might benefit from a different layout than mobile phones.
Microinteractions: Adding small animations or feedback when users interact with elements (e.g., swiping a recipe, tapping a button) could make the app feel more responsive and engaging.
Feedback on Errors: Ensure that the UI design includes visual cues for error states (e.g., invalid input fields during sign-up or network issues during API calls). These cues help users understand what went wrong and how to correct it.
Overall, your Figma design showcases a well-structured and user-focused approach, with thoughtful categorization and feature prioritization. By addressing a few areas like error handling, offline support, and enhanced navigation, the design can become even more robust and user-friendly.

**Comment by Ylanv** [comment]
Thank you for the detailed feedback and suggestions. I appreciate your positive comments on the application architecture, user flow, and user stories. Regarding the areas for improvement, I completely agree that error handling, offline support, and edge cases are crucial aspects to address, and we’ll work on improving those. I also appreciate your thoughts on the onboarding experience and secondary navigation, which we’ll refine further.

Thanks again for your valuable input, and I’ll make sure to incorporate these enhancements moving forward!

**Review by CapraSnitzel — APPROVED** [review]
After reading your message, it is much clearer now.

**Pull request merged**
